export enum Constants {
  SDK = 'OPEN_TELEMETRY_SDK',
  SDK_CONFIG = 'OPEN_TELEMETRY_SDK_CONFIG',
  SDK_INJECTORS = 'SDK_INJECTORS',
  TRACE_METADATA = 'OPEN_TELEMETRY_TRACE_METADATA',
  METRIC_METADATA = 'OPEN_TELEMETRY_METRIC_METADATA',
  TRACE_METADATA_ACTIVE = 'OPEN_TELEMETRY_TRACE_METADATA_ACTIVE',
  METRIC_METADATA_ACTIVE = 'OPEN_TELEMETRY_METRIC_METADATA_ACTIVE',
}
